apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx

    spec:
      containers:
      - name: mynginx
        image: nginx:1.20
        ports:
        - containerPort: 80
